name: np_dbs
channels:
- intel
- conda-forge
- defaults
dependencies:
- alsa-lib=1.1.5=0
- ca-certificates=2018.1.18=0
- certifi=2018.1.18=py36_0
- cython=0.28.1=py36_0
- dbus=1.10.22=0
- expat=2.2.5=0
- fontconfig=2.12.6=0
- freetype=2.8.1=0
- gettext=0.19.8.1=0
- glib=2.55.0=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=1
- icu=58.2=0
- jpeg=9b=2
- libffi=3.2.1=3
- libiconv=1.15=0
- libpng=1.6.34=0
- libxcb=1.13=0
- libxml2=2.9.8=0
- ncurses=5.9=10
- openssl=1.0.2n=0
- pcre=8.41=1
- pip=9.0.2=py36_0
- portaudio=19.6.0=0
- pyqt=5.6.0=py36_4
- pyqtgraph=0.10.0=py36_2
- pyserial=3.4=py36_0
- python=3.6.4=0
- qt=5.6.2=7
- qtpy=1.4.0=py36_0
- readline=7.0=0
- setuptools=39.0.1=py36_0
- sip=4.18=py36_1
- sqlite=3.20.1=2
- tk=8.6.7=0
- wheel=0.30.0=py36_2
- xorg-libxau=1.0.8=3
- xorg-libxdmcp=1.1.2=3
- xz=5.2.3=0
- zlib=1.2.11=0
- libgcc=7.2.0=h69d50b8_2
- libgcc-ng=7.2.0=hdf63c60_3
- libstdcxx-ng=7.2.0=hdf63c60_3
- icc_rt=2018.0.0=intel_0
- intelpython=2018.0.0=3
- mkl=2018.0.1=intel_4
- mkl_fft=1.0.0=np113py36_intel_15
- mkl_random=1.0.0=np113py36_intel_6
- numpy=1.13.3=py36_intel_6
- openmp=2018.0.0=intel_8
- scipy=0.19.1=np113py36_intel_23
- pip:
  - https://github.com/dashesy/CereLink/releases/download/7.0/cerebus-0.0.3-cp36-cp36m-linux_x86_64.whl
  - git+https://github.com/SachsLab/cerebuswrapper.git
  - mkl-random==1.0.0
  - pyaudio==0.2.11

